window.THUMBHASH_DEMO = {
  "generatedWith": "ThumbHashSharp 2.0.0",
  "resizeMode": "Area",
  "images": [
    {
      "title": "阳朔翠屏全景",
      "kind": "超宽全景 · JPEG",
      "layout": "wide",
      "source": "assets/images/yangshuo-panorama.jpg",
      "placeholder": "assets/placeholders/yangshuo-panorama.png",
      "width": 1439,
      "height": 563,
      "fileBytes": 220592,
      "hashBytes": 17,
      "thumbHash": "lhgOC4J3iHd/h8h4NmBf9NY=",
      "averageColor": "rgb(102 90 76)",
      "author": "Chensiyuan",
      "license": "CC BY-SA 4.0",
      "sourcePage": "https://commons.wikimedia.org/wiki/File:1_pano_cuiping_yangshuo_2016.jpg"
    },
    {
      "title": "圣托里尼巷道",
      "kind": "竖幅建筑 · WebP",
      "layout": "tall",
      "source": "assets/images/santorini-architecture.webp",
      "placeholder": "assets/placeholders/santorini-architecture.png",
      "width": 954,
      "height": 1440,
      "fileBytes": 150694,
      "hashBytes": 21,
      "thumbHash": "GhkSHQIHeJR5aIhXl3Z4d8OAOQ6n",
      "averageColor": "rgb(123 111 81)",
      "author": "Norbert Nagel",
      "license": "CC BY-SA 3.0",
      "sourcePage": "https://commons.wikimedia.org/wiki/File:07-17-2012_-_Emborio_-_Emporio_-_Santorini_-_Greece_-_11.jpg"
    },
    {
      "title": "舍夫沙万蓝城",
      "kind": "高饱和街景 · AVIF",
      "layout": "standard",
      "source": "assets/images/blue-city.avif",
      "placeholder": "assets/placeholders/blue-city.png",
      "width": 1440,
      "height": 960,
      "fileBytes": 408725,
      "hashBytes": 21,
      "thumbHash": "nuYFHYLJdXl/aIiJh3d4iNqPuv2o",
      "averageColor": "rgb(101 113 151)",
      "author": "Fbrandao.1963",
      "license": "CC BY-SA 4.0",
      "sourcePage": "https://commons.wikimedia.org/wiki/File:2018_01_(Blue)_-_Chaouen.jpg"
    },
    {
      "title": "湖上独木舟",
      "kind": "旅行纪实 · JPEG",
      "layout": "standard",
      "source": "assets/images/lake-canoe.jpg",
      "placeholder": "assets/placeholders/lake-canoe.png",
      "width": 1440,
      "height": 960,
      "fileBytes": 135360,
      "hashBytes": 21,
      "thumbHash": "XscNDYS+aHidc3hviNh3RAw+wuBE",
      "averageColor": "rgb(101 129 135)",
      "author": "Roberto Nickson",
      "license": "Unsplash License",
      "sourcePage": "https://unsplash.com/photos/7BjmDICVloE"
    },
    {
      "title": "窗边人物肖像",
      "kind": "竖幅人像 · WebP",
      "layout": "tall",
      "source": "assets/images/portrait.webp",
      "placeholder": "assets/placeholders/portrait.png",
      "width": 960,
      "height": 1440,
      "fileBytes": 56110,
      "hashBytes": 21,
      "thumbHash": "UxgGDQI/etJ2q5VYmWeIlwOjNjBK",
      "averageColor": "rgb(87 75 69)",
      "author": "Roksolana Zasiadko",
      "license": "Unsplash License",
      "sourcePage": "https://unsplash.com/photos/LyeduBb2Auk"
    },
    {
      "title": "新鲜草莓",
      "kind": "高饱和食物 · JPEG",
      "layout": "standard",
      "source": "assets/images/strawberries.jpg",
      "placeholder": "assets/placeholders/strawberries.png",
      "width": 1440,
      "height": 960,
      "fileBytes": 333509,
      "hashBytes": 21,
      "thumbHash": "18gGBYJImqN8lVlgSNlXdmdf5dkH",
      "averageColor": "rgb(153 52 74)",
      "author": "veeterzy",
      "license": "Unsplash License",
      "sourcePage": "https://unsplash.com/photos/OJJIaFZOeX4"
    },
    {
      "title": "黑色幼犬",
      "kind": "动物特写 · AVIF",
      "layout": "standard",
      "source": "assets/images/black-puppy.avif",
      "placeholder": "assets/placeholders/black-puppy.png",
      "width": 1440,
      "height": 862,
      "fileBytes": 186274,
      "hashBytes": 19,
      "thumbHash": "lBgKDILLCjdniol7cpr4Z4x/tg==",
      "averageColor": "rgb(94 82 67)",
      "author": "André Spieker",
      "license": "Unsplash License",
      "sourcePage": "https://unsplash.com/photos/8wTPqxlnKM4"
    },
    {
      "title": "透明仙人掌图标",
      "kind": "透明插画 · PNG",
      "layout": "standard",
      "source": "assets/images/transparent-cactus.png",
      "placeholder": "assets/placeholders/transparent-cactus.png",
      "width": 618,
      "height": 618,
      "fileBytes": 9265,
      "hashBytes": 25,
      "thumbHash": "l9qBBQAlKPd0enW7pwhydN+oB4iHeHGKhw==",
      "averageColor": "rgb(111 132 36)",
      "author": "OpenMoji contributors",
      "license": "CC BY-SA 4.0",
      "sourcePage": "https://github.com/hfg-gmuend/openmoji/blob/master/color/618x618/1F335.png"
    },
    {
      "title": "星空灯塔",
      "kind": "夜景建筑 · WebP",
      "layout": "tall",
      "source": "assets/images/lighthouse.webp",
      "placeholder": "assets/placeholders/lighthouse.png",
      "width": 963,
      "height": 1440,
      "fileBytes": 100570,
      "hashBytes": 21,
      "thumbHash": "WqYNRQqJeHOHCIfXiIO3Z2lwmwXW",
      "averageColor": "rgb(65 110 140)",
      "author": "Joshua Hibbert",
      "license": "Unsplash License",
      "sourcePage": "https://unsplash.com/photos/Pn6iimgM-wo"
    }
  ]
};
